# fly.toml app configuration file generated for xflux-api on 2026-07-04T12:12:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xflux-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  CONSUMER_API_BASE_URL = 'http://89.167.53.180'
  CONSUMER_API_PREFIX = '/consumer'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
