import { makeTopic } from "./make-topic";
import type { SignalTopicConfig } from "./topic-types";

/** Long-tail and sub-niche verticals — SEO long-tail + specialist monitor use cases. */
export const NICHE_SIGNAL_TOPICS: SignalTopicConfig[] = [
  // ── AI sub-niches ───────────────────────────────────────────────
  makeTopic({
    slug: "prompt-engineering",
    category: "niche",
    title: "Prompt Engineering",
    pageTitle: "Live Prompt Engineering Signals on X — LLM Prompts & Eval Tips",
    description:
      "Prompt patterns, jailbreak research, and LLM eval tricks from prompt engineers on X/Twitter.",
    keywords: ["prompt engineering Twitter", "LLM prompts X", "prompt monitor alerts"],
    intro: "Prompt templates, chain-of-thought patterns, and eval workflows from practitioners.",
    watchAccounts: ["simonw", "swyx", "OpenAI", "AnthropicAI", "goodside"],
    searchQuery: '("prompt engineering" OR "system prompt" OR few-shot OR chain-of-thought) lang:en -filter:replies',
    pulseLabel: "Prompts",
  }),
  makeTopic({
    slug: "local-llm",
    category: "niche",
    title: "Local LLM & Ollama",
    pageTitle: "Live Local LLM Signals on X — Ollama, llama.cpp & On-Device AI",
    description:
      "Local model runs, Ollama recipes, and on-device AI chatter from the local LLM community on X.",
    keywords: ["local LLM Twitter", "Ollama alerts X", "llama.cpp monitor", "on-device AI feed"],
    intro: "Quantized models, local inference setups, and privacy-first AI from hobbyists and builders.",
    watchAccounts: ["ollama", "lmstudio", "simonw", "pcunning", "MaziyarPanahi"],
    searchQuery: '(Ollama OR "local LLM" OR llama.cpp OR "on-device" OR GGUF) lang:en -filter:replies',
    pulseLabel: "Local LLM",
  }),
  makeTopic({
    slug: "ai-image-video",
    category: "niche",
    title: "AI Image & Video",
    pageTitle: "Live AI Art Signals on X — Midjourney, SD & Video Models",
    description:
      "Midjourney, Stable Diffusion, Sora-style video model news from AI artists and researchers on X.",
    keywords: ["Midjourney Twitter alerts", "Stable Diffusion X", "AI video model news"],
    intro: "Model drops, prompt aesthetics, and generative video demos from creators and labs.",
    watchAccounts: ["midjourney", "StabilityAI", "Adobe", "runwayml", "simonw"],
    searchQuery: '(Midjourney OR "Stable Diffusion" OR "AI video" OR Sora OR FLUX) lang:en -filter:replies',
    pulseLabel: "AI Art",
  }),
  makeTopic({
    slug: "rag-embeddings",
    category: "niche",
    title: "RAG & Embeddings",
    pageTitle: "Live RAG Signals on X — Vector DB, Retrieval & Chunking",
    description:
      "RAG pipelines, embedding models, and vector DB comparisons from ML engineers on X/Twitter.",
    keywords: ["RAG Twitter alerts", "vector database X", "embeddings monitor", "retrieval augmented"],
    intro: "Chunking strategies, rerankers, and vector store benchmarks from production RAG builders.",
    watchAccounts: ["LangChainAI", "pinecone", "weaviate_io", "simonw", "huggingface"],
    searchQuery: '(RAG OR embeddings OR "vector database" OR reranker OR chunking) lang:en -filter:replies',
    pulseLabel: "RAG",
  }),

  // ── Crypto sub-niches ───────────────────────────────────────────
  makeTopic({
    slug: "restaking",
    category: "niche",
    title: "Restaking & LRT",
    pageTitle: "Live Restaking Signals on X — EigenLayer, LRT & AVS",
    description:
      "Restaking, liquid restaking tokens, and AVS launches from EigenLayer ecosystem on X.",
    keywords: ["restaking Twitter", "EigenLayer alerts", "LRT crypto X", "AVS monitor"],
    intro: "LRT yields, operator news, and restaking risk discourse from DeFi researchers.",
    watchAccounts: ["eigenlayer", "LidoFinance", "ether_fi", "RenzoProtocol", "DefiIgnas"],
    searchQuery: '(restaking OR EigenLayer OR LRT OR AVS OR "liquid restaking") lang:en -filter:replies',
    pulseLabel: "Restaking",
  }),
  makeTopic({
    slug: "ordinals-runes",
    category: "niche",
    title: "Ordinals & Runes",
    pageTitle: "Live Ordinals Signals on X — Bitcoin Inscriptions & Runes",
    description:
      "Bitcoin ordinals, runes, and inscription marketplace chatter on X/Twitter.",
    keywords: ["ordinals Twitter alerts", "Bitcoin inscriptions X", "runes BTC monitor"],
    intro: "Inscription drops, rune launches, and Bitcoin L1 NFT/meta discourse.",
    watchAccounts: ["rodarmor", "OrdinalsWallet", "LeonidasNFT", "ordinalswallet", "lookonchain"],
    searchQuery: '(ordinals OR inscriptions OR runes OR "Bitcoin NFT") lang:en -filter:replies',
    pulseLabel: "Ordinals",
  }),
  makeTopic({
    slug: "memecoins",
    category: "niche",
    title: "Memecoins",
    pageTitle: "Live Memecoin Signals on X — Degen Trades & New Launches",
    description:
      "Memecoin launches, degen alpha, and pump.fun chatter from crypto traders on X.",
    keywords: ["memecoin Twitter alerts", "degen crypto X", "pump.fun monitor", "meme coin launch"],
    intro: "New token launches, liquidity events, and memecoin narrative cycles — high velocity.",
    watchAccounts: ["lookonchain", "DefiIgnas", "cobie", "CryptoKaleo", "blknoiz06"],
    searchQuery: '(memecoin OR memecoins OR degen OR pump.fun OR "new token") lang:en -filter:replies',
    pulseLabel: "Memes",
  }),
  makeTopic({
    slug: "base-chain",
    category: "niche",
    title: "Base Ecosystem",
    pageTitle: "Live Base Chain Signals on X — Coinbase L2 & Onchain Apps",
    description:
      "Base L2 app launches, onchain social, and Coinbase chain ecosystem news on X.",
    keywords: ["Base chain Twitter", "Coinbase L2 alerts", "Base ecosystem monitor"],
    intro: "Base app deployments, Farcaster crossover, and L2 builder updates from the ecosystem.",
    watchAccounts: ["base", "jessepollak", "coinbase", "BuildOnBase", "dwr"],
    searchQuery: '(Base OR "Build on Base" OR @base OR "Coinbase L2") lang:en -filter:replies',
    pulseLabel: "Base",
  }),

  // ── Markets sub-niches ──────────────────────────────────────────
  makeTopic({
    slug: "options-trading",
    category: "niche",
    title: "Options Trading",
    pageTitle: "Live Options Signals on X — Greeks, Flow & Volatility",
    description:
      "Options flow, volatility trades, and greek chatter from options traders on X/Twitter.",
    keywords: ["options trading Twitter", "options flow alerts", "volatility X monitor"],
    intro: "Unusual options activity, vol surface moves, and earnings play discussion.",
    watchAccounts: ["unusual_whales", "OptionsHawk", "SqueezeMetrics", "SpotGamma", "Tier1Alpha"],
    searchQuery: '(options OR "options flow" OR gamma OR vega OR volatility trading) lang:en -filter:replies',
    pulseLabel: "Options",
  }),
  makeTopic({
    slug: "small-caps",
    category: "niche",
    title: "Small Caps & Microcaps",
    pageTitle: "Live Small Cap Signals on X — Penny Stocks & Low Float",
    description:
      "Small cap runners, low-float setups, and microcap diligence from traders on X.",
    keywords: ["small cap Twitter alerts", "penny stock X", "microcap monitor", "low float trading"],
    intro: "Runner alerts, dilution risks, and microcap catalyst hunting from active traders.",
    watchAccounts: ["SmallCapScience", "BioStocks", "Trade_The_News", "unusual_whales", "Stocktwits"],
    searchQuery: '(small cap OR microcap OR "penny stock" OR "low float" OR runner) lang:en -filter:replies',
    pulseLabel: "Small Cap",
  }),
  makeTopic({
    slug: "dividend-investing",
    category: "niche",
    title: "Dividend Investing",
    pageTitle: "Live Dividend Signals on X — Yield, DRIP & Income",
    description:
      "Dividend growth, yield traps, and income portfolio chatter from dividend investors on X.",
    keywords: ["dividend investing Twitter", "dividend stocks alerts", "yield X monitor"],
    intro: "Dividend hikes, cut warnings, and income strategy threads from long-term holders.",
    watchAccounts: ["DividendGrowth", "SureDividend", "SeekingAlpha", "elerianm", "DeItaone"],
    searchQuery: '(dividend OR "dividend yield" OR DRIP OR "income investing" OR "dividend growth") lang:en -filter:replies',
    pulseLabel: "Dividends",
  }),
  makeTopic({
    slug: "quant-trading",
    category: "niche",
    title: "Quant & Systematic",
    pageTitle: "Live Quant Trading Signals on X — Algos, Factors & Backtests",
    description:
      "Quant finance, systematic strategies, and backtest discourse from quants on X.",
    keywords: ["quant trading Twitter", "systematic investing X", "algo trading monitor"],
    intro: "Factor research, strategy leaks, and quant hiring from funds and indie quants.",
    watchAccounts: ["quantocracy", "KirkDBorne", "fchollet", "eugenewu", "markten"],
    searchQuery: '(quant OR "systematic trading" OR backtest OR "factor investing" OR alpha) lang:en -filter:replies',
    pulseLabel: "Quant",
  }),

  // ── Business sub-niches ─────────────────────────────────────────
  makeTopic({
    slug: "customer-success",
    category: "niche",
    title: "Customer Success",
    pageTitle: "Live CS Signals on X — Retention, NRR & Onboarding",
    description:
      "Customer success tactics, churn prevention, and NRR benchmarks from CS leaders on X.",
    keywords: ["customer success Twitter", "CS leader alerts", "churn reduction X", "NRR monitor"],
    intro: "Onboarding playbooks, QBR templates, and expansion motion from CS operators.",
    watchAccounts: ["clairejlew", "darmesh", "HitenShah", "patio11", "lennysan"],
    searchQuery: '("customer success" OR CS OR churn OR NRR OR "net revenue retention") lang:en -filter:replies',
    pulseLabel: "CS",
  }),
  makeTopic({
    slug: "revops",
    category: "niche",
    title: "RevOps & Sales Ops",
    pageTitle: "Live RevOps Signals on X — CRM, Pipeline & GTM Data",
    description:
      "RevOps, Salesforce tips, and pipeline hygiene from revenue operations pros on X.",
    keywords: ["RevOps Twitter alerts", "sales ops X", "GTM data monitor", "CRM workflow"],
    intro: "CRM automation, lead routing, and forecast accuracy tactics from RevOps builders.",
    watchAccounts: ["hubspot", "salesforce", "clairejlew", "patio11", "elenaverna"],
    searchQuery: '(RevOps OR "revenue operations" OR Salesforce OR "pipeline hygiene" OR GTM) lang:en -filter:replies',
    pulseLabel: "RevOps",
  }),
  makeTopic({
    slug: "recruiting",
    category: "niche",
    title: "Recruiting & Talent",
    pageTitle: "Live Recruiting Signals on X — Hiring, Tech Jobs & HR",
    description:
      "Tech hiring, layoff waves, and recruiter tactics from talent leaders on X/Twitter.",
    keywords: ["tech recruiting Twitter", "hiring alerts X", "HR monitor", "talent acquisition feed"],
    intro: "Open roles, compensation trends, and hiring market shifts from recruiters and founders.",
    watchAccounts: ["jason", "paulg", "levelsio", "LayoffsTracker", "hiring"],
    searchQuery: '(recruiting OR hiring OR "talent acquisition" OR layoffs OR "open role") lang:en -filter:replies',
    pulseLabel: "Hiring",
  }),
  makeTopic({
    slug: "newsletter-creator",
    category: "niche",
    title: "Newsletters & Creators",
    pageTitle: "Live Newsletter Signals on X — Substack, Growth & Monetization",
    description:
      "Newsletter growth, Substack tactics, and creator monetization from writers on X.",
    keywords: ["newsletter Twitter alerts", "Substack growth X", "creator economy monitor"],
    intro: "Launch threads, sponsorship deals, and subscriber growth playbooks from creators.",
    watchAccounts: ["SubstackInc", "lennysan", "dickiebush", "AliAbdaal", "fortelabs"],
    searchQuery: '(newsletter OR Substack OR "creator economy" OR monetization OR subscribers) lang:en -filter:replies',
    pulseLabel: "Newsletter",
  }),
  makeTopic({
    slug: "freelancing",
    category: "niche",
    title: "Freelancing & Consulting",
    pageTitle: "Live Freelance Signals on X — Clients, Rates & Solo Business",
    description:
      "Freelance client acquisition, rate negotiation, and solo consultant tips on X.",
    keywords: ["freelancing Twitter alerts", "consulting X monitor", "solo business feed"],
    intro: "Proposal templates, scope creep war stories, and solo business ops from freelancers.",
    watchAccounts: ["patio11", "shl", "dhh", "jasonfried", "levelsio"],
    searchQuery: '(freelancing OR freelance OR consulting OR "solo consultant" OR "hourly rate") lang:en -filter:replies',
    pulseLabel: "Freelance",
  }),

  // ── Developer sub-niches ────────────────────────────────────────
  makeTopic({
    slug: "golang",
    category: "niche",
    title: "Go / Golang",
    pageTitle: "Live Go Signals on X — Golang Releases & Backend Patterns",
    description:
      "Go language updates, concurrency patterns, and backend Go chatter on X/Twitter.",
    keywords: ["Golang Twitter alerts", "Go programming X", "Go backend monitor"],
    intro: "Go releases, stdlib changes, and production Go patterns from maintainers and teams.",
    watchAccounts: ["golang", "bradfitz", "rsc", "jbd", "davecheney"],
    searchQuery: '(Golang OR "Go language" OR goroutine OR "Go 1.") lang:en -filter:replies',
    pulseLabel: "Go",
  }),
  makeTopic({
    slug: "postgres",
    category: "niche",
    title: "PostgreSQL",
    pageTitle: "Live Postgres Signals on X — SQL, Extensions & Performance",
    description:
      "PostgreSQL tips, extension releases, and query tuning from DB engineers on X.",
    keywords: ["PostgreSQL Twitter alerts", "Postgres performance X", "SQL monitor feed"],
    intro: "Index strategies, pgvector, and Postgres ops war stories from database specialists.",
    watchAccounts: ["postgres", "simonw", "kelseyhightower", "beberlei", "pganalyze"],
    searchQuery: '(PostgreSQL OR Postgres OR pgvector OR SQL OR "query tuning") lang:en -filter:replies',
    pulseLabel: "Postgres",
  }),
  makeTopic({
    slug: "self-hosting",
    category: "niche",
    title: "Self-Hosting & Homelab",
    pageTitle: "Live Homelab Signals on X — Proxmox, NAS & Self-Hosted Apps",
    description:
      "Homelab builds, self-hosted app stacks, and Proxmox tips from homelabbers on X.",
    keywords: ["homelab Twitter alerts", "self-hosting X", "Proxmox monitor", "NAS homelab feed"],
    intro: "Docker stacks, VLAN setups, and self-hosted alternatives from homelab enthusiasts.",
    watchAccounts: ["kelseyhightower", "simonw", "sindresorhus", "HomeAssistant", "Tailscale"],
    searchQuery: '(homelab OR "self-hosted" OR Proxmox OR NAS OR "self hosting") lang:en -filter:replies',
    pulseLabel: "Homelab",
  }),
  makeTopic({
    slug: "no-code",
    category: "niche",
    title: "No-Code & Low-Code",
    pageTitle: "Live No-Code Signals on X — Bubble, Webflow & Automations",
    description:
      "No-code builds, Webflow launches, and automation workflows from makers on X.",
    keywords: ["no-code Twitter alerts", "Webflow monitor X", "Bubble.io feed", "low-code automation"],
    intro: "Template drops, agency tactics, and citizen developer workflows from no-code builders.",
    watchAccounts: ["webflow", "bubble", "zapier", "MakeHQ", "GlideApps"],
    searchQuery: '("no-code" OR "low-code" OR Webflow OR Bubble OR "citizen developer") lang:en -filter:replies',
    pulseLabel: "No-Code",
  }),
  makeTopic({
    slug: "technical-writing",
    category: "niche",
    title: "Technical Writing",
    pageTitle: "Live Tech Writing Signals on X — Docs, DevRel & API Docs",
    description:
      "Technical writing, developer docs, and DevRel content strategy from writers on X.",
    keywords: ["technical writing Twitter", "developer docs alerts", "DevRel content X"],
    intro: "Docs-as-code, API reference patterns, and content ops from technical writers.",
    watchAccounts: ["swyx", "simonw", "kelseyhightower", "rauchg", "AmyWritesTech"],
    searchQuery: '("technical writing" OR "developer docs" OR DevRel OR "API documentation") lang:en -filter:replies',
    pulseLabel: "Tech Writing",
  }),

  // ── Security sub-niches ─────────────────────────────────────────
  makeTopic({
    slug: "bug-bounty",
    category: "niche",
    title: "Bug Bounty & Pentest",
    pageTitle: "Live Bug Bounty Signals on X — HackerOne, CVE & Pentesting",
    description:
      "Bug bounty writeups, pentest techniques, and disclosure chatter from security researchers.",
    keywords: ["bug bounty Twitter alerts", "pentest X monitor", "HackerOne feed", "security researcher"],
    intro: "Bounty payouts, novel exploit chains, and recon tips from active hunters.",
    watchAccounts: ["Hacker0x01", "ippsec", "LiveOverflow", "NahamSec", "InsiderPhD"],
    searchQuery: '("bug bounty" OR pentest OR HackerOne OR "responsible disclosure" OR recon) lang:en -filter:replies',
    pulseLabel: "Bounty",
  }),
  makeTopic({
    slug: "osint",
    category: "niche",
    title: "OSINT",
    pageTitle: "Live OSINT Signals on X — Open Source Intelligence & Investigations",
    description:
      "OSINT techniques, investigation threads, and geolocation tricks from OSINT practitioners on X.",
    keywords: ["OSINT Twitter alerts", "open source intelligence X", "OSINT monitor feed"],
    intro: "Investigation workflows, tool drops, and verification methods from OSINT community.",
    watchAccounts: ["Bellingcat", "IntelCrab", "GeoConfirmed", "AricToler", "Quiztime"],
    searchQuery: '(OSINT OR "open source intelligence" OR geolocation OR investigation OR Bellingcat) lang:en -filter:replies',
    pulseLabel: "OSINT",
  }),

  // ── Industry verticals ──────────────────────────────────────────
  makeTopic({
    slug: "legal-tech",
    category: "niche",
    title: "Legal Tech",
    pageTitle: "Live Legal Tech Signals on X — AI Law Tools & Legal Ops",
    description:
      "Legal tech startups, contract AI, and legal ops automation from lawyers and founders on X.",
    keywords: ["legal tech Twitter alerts", "legal AI monitor", "legal ops X feed"],
    intro: "Contract review AI, legal workflow automation, and bar-adjacent product launches.",
    watchAccounts: ["LegalTechNews", "Harvey", "Ironclad", "Clio", "lawfare"],
    searchQuery: '("legal tech" OR "legal AI" OR "contract AI" OR "legal ops" OR paralegal) lang:en -filter:replies',
    pulseLabel: "LegalTech",
  }),
  makeTopic({
    slug: "edtech",
    category: "niche",
    title: "EdTech",
    pageTitle: "Live EdTech Signals on X — Learning Apps & Online Courses",
    description:
      "EdTech product launches, course creator tactics, and learning science on X/Twitter.",
    keywords: ["EdTech Twitter alerts", "online course X", "learning app monitor"],
    intro: "LMS updates, cohort course playbooks, and education startup funding chatter.",
    watchAccounts: ["Coursera", "khanacademy", "Duolingo", "AliAbdaal", "AndrewYNg"],
    searchQuery: '(EdTech OR "online course" OR LMS OR "learning app" OR cohort) lang:en -filter:replies',
    pulseLabel: "EdTech",
  }),
  makeTopic({
    slug: "healthtech",
    category: "niche",
    title: "Health Tech",
    pageTitle: "Live Health Tech Signals on X — Digital Health & Telemedicine",
    description:
      "Digital health apps, telemedicine, and health startup news from builders on X.",
    keywords: ["health tech Twitter alerts", "digital health X", "telemedicine monitor"],
    intro: "FDA clearance news, RPM devices, and health API integrations from healthtech founders.",
    watchAccounts: ["EricTopol", "statnews", "Rock_Health", "a16z", "FoundersFund"],
    searchQuery: '("health tech" OR "digital health" OR telemedicine OR "FDA clearance" OR RPM) lang:en -filter:replies',
    pulseLabel: "HealthTech",
  }),
  makeTopic({
    slug: "agtech",
    category: "niche",
    title: "AgTech & Food",
    pageTitle: "Live AgTech Signals on X — Farming Tech & Food Supply",
    description:
      "AgTech, precision farming, and food supply chain tech from founders and analysts on X.",
    keywords: ["AgTech Twitter alerts", "precision farming X", "food tech monitor"],
    intro: "Drone spraying, vertical farming, and ag data platform updates from the field.",
    watchAccounts: ["FAO", "USDA", "IndoorAgTech", "AgFunder", "foodtechconnect"],
    searchQuery: '(AgTech OR agritech OR "precision farming" OR "vertical farming" OR "food tech") lang:en -filter:replies',
    pulseLabel: "AgTech",
  }),
  makeTopic({
    slug: "logistics",
    category: "niche",
    title: "Logistics & Supply Chain",
    pageTitle: "Live Logistics Signals on X — Freight, Warehousing & 3PL",
    description:
      "Supply chain disruptions, freight rates, and logistics tech from operators on X.",
    keywords: ["logistics Twitter alerts", "supply chain X monitor", "freight news feed"],
    intro: "Port congestion, last-mile tech, and warehouse automation from logistics pros.",
    watchAccounts: ["freightwaves", "SupplyChainDive", "Flexport", "project44", "Convoy"],
    searchQuery: '(logistics OR "supply chain" OR freight OR warehousing OR 3PL) lang:en -filter:replies',
    pulseLabel: "Logistics",
  }),
  makeTopic({
    slug: "nonprofit",
    category: "niche",
    title: "Nonprofit & Impact",
    pageTitle: "Live Nonprofit Signals on X — Fundraising & Social Impact",
    description:
      "Nonprofit fundraising, grant news, and social impact org updates on X/Twitter.",
    keywords: ["nonprofit Twitter alerts", "social impact X", "fundraising monitor NGO"],
    intro: "Grant cycles, donor trends, and impact measurement from nonprofit leaders.",
    watchAccounts: ["GivingTuesday", "gatesfoundation", "CharityWatch", "NonprofitTimes", "UN"],
    searchQuery: '(nonprofit OR NGO OR "social impact" OR fundraising OR grant) lang:en -filter:replies',
    pulseLabel: "Nonprofit",
  }),

  // ── Science & health sub-niches ─────────────────────────────────
  makeTopic({
    slug: "longevity",
    category: "niche",
    title: "Longevity & Biohacking",
    pageTitle: "Live Longevity Signals on X — Anti-Aging & Healthspan",
    description:
      "Longevity research, biohacking protocols, and healthspan chatter from scientists on X.",
    keywords: ["longevity Twitter alerts", "biohacking X monitor", "anti-aging research feed"],
    intro: "Rapamycin discourse, biomarker tracking, and longevity startup news.",
    watchAccounts: ["EricTopol", "DavidSinclair", "foundmyfitness", "PeterAttiaMD", "bryan_johnson"],
    searchQuery: '(longevity OR biohacking OR healthspan OR "anti-aging" OR NAD) lang:en -filter:replies',
    pulseLabel: "Longevity",
  }),
  makeTopic({
    slug: "neuroscience",
    category: "niche",
    title: "Neuroscience",
    pageTitle: "Live Neuroscience Signals on X — Brain Research & BCI",
    description:
      "Neuroscience papers, brain-computer interfaces, and neurology news on X/Twitter.",
    keywords: ["neuroscience Twitter alerts", "BCI monitor X", "brain research feed"],
    intro: "Neuralink updates, cognitive science threads, and lab preprints from neuro researchers.",
    watchAccounts: ["Neuro_Skeptic", "NatureNeuro", "Neuralink", "EricTopol", "hubermanlab"],
    searchQuery: '(neuroscience OR BCI OR "brain-computer" OR neurology OR Neuralink) lang:en -filter:replies',
    pulseLabel: "Neuro",
  }),
  makeTopic({
    slug: "fitness-nutrition",
    category: "niche",
    title: "Fitness & Nutrition",
    pageTitle: "Live Fitness Signals on X — Training, Macros & Wellness",
    description:
      "Fitness programming, nutrition science, and wellness trends from coaches on X.",
    keywords: ["fitness Twitter alerts", "nutrition X monitor", "workout feed", "macro tracking"],
    intro: "Training splits, supplement discourse, and evidence-based nutrition threads.",
    watchAccounts: ["hubermanlab", "foundmyfitness", "PeterAttiaMD", "CrossFit", "WHO"],
    searchQuery: '(fitness OR nutrition OR macros OR "strength training" OR wellness) lang:en -filter:replies',
    pulseLabel: "Fitness",
  }),

  // ── Culture sub-niches ──────────────────────────────────────────
  makeTopic({
    slug: "anime",
    category: "niche",
    title: "Anime & Manga",
    pageTitle: "Live Anime Signals on X — Releases, Studios & Fandom",
    description:
      "Anime season announcements, manga releases, and studio news from fandom on X.",
    keywords: ["anime Twitter alerts", "manga news X", "anime season monitor"],
    intro: "Seasonal anime drops, adaptation news, and creator announcements from the community.",
    watchAccounts: ["Crunchyroll", "aniplexUSA", "KADOKAWA", "MangaPlus", "Anime"],
    searchQuery: '(anime OR manga OR "anime season" OR Crunchyroll OR "new episode") lang:en -filter:replies',
    pulseLabel: "Anime",
  }),
  makeTopic({
    slug: "mechanical-keyboards",
    category: "niche",
    title: "Mechanical Keyboards",
    pageTitle: "Live Mech Keyboard Signals on X — Group Buys & Switches",
    description:
      "Mechanical keyboard group buys, switch reviews, and custom build chatter on X.",
    keywords: ["mechanical keyboard Twitter", "group buy alerts X", "keyboard switches monitor"],
    intro: "IC drops, switch sound tests, and custom keyboard build threads from enthusiasts.",
    watchAccounts: ["keychron", "Drop", "NovelKeys", "TaehaTypes", "SwitchAndClick"],
    searchQuery: '("mechanical keyboard" OR "group buy" OR switches OR keycap OR "custom keyboard") lang:en -filter:replies',
    pulseLabel: "Mech KB",
  }),
  makeTopic({
    slug: "vinyl-audio",
    category: "niche",
    title: "Vinyl & Audiophile",
    pageTitle: "Live Vinyl Signals on X — Records, Hi-Fi & Audio Gear",
    description:
      "Vinyl reissues, audiophile gear, and hi-fi review chatter from collectors on X.",
    keywords: ["vinyl Twitter alerts", "audiophile X monitor", "hi-fi gear feed", "record collecting"],
    intro: "Reissue announcements, turntable setups, and DAC comparisons from audio nerds.",
    watchAccounts: ["Discogs", "pitchfork", "Stereogum", "MoFi", "AudioScience"],
    searchQuery: '(vinyl OR audiophile OR "hi-fi" OR turntable OR reissue) lang:en -filter:replies',
    pulseLabel: "Vinyl",
  }),
  makeTopic({
    slug: "specialty-coffee",
    category: "niche",
    title: "Specialty Coffee",
    pageTitle: "Live Coffee Signals on X — Roasters, Beans & Barista",
    description:
      "Specialty coffee roasters, origin drops, and barista technique from coffee community on X.",
    keywords: ["specialty coffee Twitter", "coffee roaster alerts", "barista X feed"],
    intro: "Single-origin drops, brew recipe threads, and roaster competition results.",
    watchAccounts: ["Starbucks", "BlueBottle", "OnyxCoffeeLab", "James_Hoffmann", "BaristaMag"],
    searchQuery: '("specialty coffee" OR roaster OR barista OR espresso OR "single origin") lang:en -filter:replies',
    pulseLabel: "Coffee",
  }),
  makeTopic({
    slug: "parenting",
    category: "niche",
    title: "Parenting",
    pageTitle: "Live Parenting Signals on X — Family, Kids & Education",
    description:
      "Parenting tips, family product launches, and education-at-home discourse on X.",
    keywords: ["parenting Twitter alerts", "family X monitor", "kids education feed"],
    intro: "Product recs, school policy debates, and family workflow hacks from parents.",
    watchAccounts: ["Parents", "CommonSense", "SesameStreet", "UNICEF", "TodayParents"],
    searchQuery: '(parenting OR "parenting tips" OR toddlers OR homeschool OR family) lang:en -filter:replies',
    pulseLabel: "Parenting",
  }),
  makeTopic({
    slug: "3d-printing",
    category: "niche",
    title: "3D Printing & Makers",
    pageTitle: "Live 3D Printing Signals on X — FDM, Resin & Maker Projects",
    description:
      "3D printer upgrades, maker projects, and filament reviews from the maker community on X.",
    keywords: ["3D printing Twitter alerts", "maker X monitor", "FDM printer feed", "resin printing"],
    intro: "Printer mod threads, STL drops, and maker faire announcements from hobbyists.",
    watchAccounts: ["Prusa3D", "Creality", "Adafruit", "SparkFun", "make"],
    searchQuery: '("3D printing" OR FDM OR resin OR maker OR STL OR Prusa) lang:en -filter:replies',
    pulseLabel: "3D Print",
  }),
  makeTopic({
    slug: "fpv-drones",
    category: "niche",
    title: "FPV & Drones",
    pageTitle: "Live FPV Drone Signals on X — Racing, Freestyle & UAV",
    description:
      "FPV drone builds, freestyle clips, and UAV regulation news from pilots on X.",
    keywords: ["FPV drone Twitter alerts", "drone racing X", "UAV monitor feed"],
    intro: "New frame drops, Betaflight updates, and drone regulation policy threads.",
    watchAccounts: ["DJIEnterprise", "BetaflightF", "iFlightRC", "DroneDJ", "FAANews"],
    searchQuery: '(FPV OR drone OR UAV OR Betaflight OR "drone racing") lang:en -filter:replies',
    pulseLabel: "FPV",
  }),
  makeTopic({
    slug: "accessibility",
    category: "niche",
    title: "Accessibility (a11y)",
    pageTitle: "Live a11y Signals on X — WCAG, Inclusive Design & ARIA",
    description:
      "Web accessibility, WCAG updates, and inclusive design from a11y advocates on X.",
    keywords: ["accessibility Twitter alerts", "a11y monitor X", "WCAG feed", "inclusive design"],
    intro: "Audit findings, screen reader tips, and accessibility law updates from practitioners.",
    watchAccounts: ["a11y", "Heydon", "LeonieWatson", "W3C", "Microsoft"],
    searchQuery: '(a11y OR accessibility OR WCAG OR ARIA OR "inclusive design") lang:en -filter:replies',
    pulseLabel: "a11y",
  }),

  // ── Product integration niches ──────────────────────────────────
  makeTopic({
    slug: "slack-alerts",
    category: "niche",
    title: "Slack Integrations",
    pageTitle: "Live Slack Integration Signals on X — Bots, Webhooks & Workflows",
    description:
      "Slack bot patterns, webhook-to-Slack workflows, and team alert stacks on X — pair with XFlux monitors.",
    keywords: ["Slack Twitter alerts integration", "Slack webhook X", "Slack bot monitor feed"],
    intro: "Slack app launches, incoming webhook patterns, and on-call alert routing tips.",
    watchAccounts: ["SlackHQ", "stripe", "GitHub", "PagerDuty", "swyx"],
    searchQuery: '(Slack OR "Slack bot" OR "Slack webhook" OR "incoming webhook") lang:en -filter:replies',
    pulseLabel: "Slack",
  }),
  makeTopic({
    slug: "discord-bots",
    category: "niche",
    title: "Discord Bots",
    pageTitle: "Live Discord Bot Signals on X — Community Alerts & Automation",
    description:
      "Discord bot development, community alert bots, and webhook bridges from builders on X.",
    keywords: ["Discord bot Twitter alerts", "Discord webhook X", "community bot monitor"],
    intro: "Bot framework updates, moderation tools, and alert bot patterns for communities.",
    watchAccounts: ["discord", "GitHub", "vercel", "swyx", "simonw"],
    searchQuery: '("Discord bot" OR Discord OR "discord webhook" OR "community bot") lang:en -filter:replies',
    pulseLabel: "Discord",
  }),
  makeTopic({
    slug: "amazon-sellers",
    category: "niche",
    title: "Amazon FBA Sellers",
    pageTitle: "Live Amazon Seller Signals on X — FBA, PPC & Account Health",
    description:
      "Amazon FBA tactics, PPC changes, and seller account health from Amazon sellers on X.",
    keywords: ["Amazon FBA Twitter alerts", "Amazon seller X monitor", "FBA PPC feed"],
    intro: "Policy changes, listing suspensions, and PPC bid strategy from active sellers.",
    watchAccounts: ["Amazon", "SellerCentral", "JungleScout", "Helium10", "ecomTom"],
    searchQuery: '("Amazon FBA" OR "Amazon seller" OR Seller Central OR "account health" OR PPC) lang:en -filter:replies',
    pulseLabel: "FBA",
  }),
  makeTopic({
    slug: "etsy-sellers",
    category: "niche",
    title: "Etsy Sellers",
    pageTitle: "Live Etsy Seller Signals on X — Handmade, SEO & Shop Tips",
    description:
      "Etsy algorithm changes, shop optimization, and handmade seller tips on X/Twitter.",
    keywords: ["Etsy seller Twitter alerts", "Etsy SEO X monitor", "handmade shop feed"],
    intro: "Fee updates, listing SEO tactics, and seasonal demand patterns from Etsy sellers.",
    watchAccounts: ["Etsy", "etsysuccess", "CreativeLive", "ecomTom", "TaylorHoliday"],
    searchQuery: '(Etsy OR "Etsy seller" OR handmade OR "Etsy SEO" OR "Etsy shop") lang:en -filter:replies',
    pulseLabel: "Etsy",
  }),
  makeTopic({
    slug: "obsidian-pkm",
    category: "niche",
    title: "Obsidian & PKM",
    pageTitle: "Live PKM Signals on X — Obsidian, Notes & Second Brain",
    description:
      "Obsidian plugins, personal knowledge management, and note-taking workflows on X.",
    keywords: ["Obsidian Twitter alerts", "PKM monitor X", "second brain feed", "note taking app"],
    intro: "Plugin releases, Zettelkasten workflows, and PKM template drops from note nerds.",
    watchAccounts: ["obsdmd", "NotionHQ", "fortelabs", "TiagoForte", "AliAbdaal"],
    searchQuery: '(Obsidian OR PKM OR "personal knowledge" OR Zettelkasten OR "second brain") lang:en -filter:replies',
    pulseLabel: "PKM",
  }),
];
