import { makeTopic } from "./make-topic";
import { NICHE_SIGNAL_TOPICS } from "./topic-catalog-niche";
import type { SignalTopicConfig } from "./topic-types";

export const SIGNAL_TOPIC_CATALOG: SignalTopicConfig[] = [
  // ── AI & Technology ─────────────────────────────────────────────
  makeTopic({
    slug: "ai",
    category: "ai-tech",
    title: "AI & LLM",
    pageTitle: "Live AI Signals on X/Twitter — LLM, Agents & Model News",
    description:
      "Free live AI signal digest on X/Twitter: @sama, @karpathy, labs, and search — who posted what, agent & model themes, and accounts to monitor with webhooks.",
    keywords: ["AI Twitter signals", "LLM news Twitter", "monitor @sama", "OpenAI Twitter alerts"],
    intro: "Model releases, agent products, safety news, and research from leading AI voices.",
    watchAccounts: ["sama", "karpathy", "DeepSeekAI", "AnthropicAI", "ylecun"],
    searchQuery: '(AI OR "artificial intelligence" OR LLM OR "ai agents") lang:en -filter:replies',
    pulseLabel: "AI",
    themeRules: [
      { label: "Safety & governance", patterns: [/safeguard|alignment|security|pause.*train/i] },
      { label: "Agent products", patterns: [/agent|computer use|browser|automate|workflow/i] },
      { label: "Model releases", patterns: [/model|api platform|release|launch|benchmark/i] },
      { label: "Research", patterns: [/training|reinforcement|frontier|research|arxiv/i] },
    ],
  }),
  makeTopic({
    slug: "ai-agents",
    category: "ai-tech",
    title: "AI Agents",
    pageTitle: "Live AI Agent Signals on X — Autonomous Tools & Workflows",
    description:
      "Track AI agent launches, computer-use demos, and workflow automation chatter on X/Twitter from builders and labs.",
    keywords: ["AI agents Twitter", "computer use agent", "autonomous AI monitor", "agent workflow X"],
    intro: "Agent frameworks, browser automation, and tool-use demos from the builders shipping them.",
    watchAccounts: ["LangChainAI", "AnthropicAI", "OpenAI", "swyx", "simonw"],
    searchQuery: '("ai agent" OR "computer use" OR "tool use" OR autogen) lang:en -filter:replies',
    pulseLabel: "Agents",
    themeRules: [
      { label: "Agent frameworks", patterns: [/langchain|crewai|autogen|framework|SDK/i] },
      { label: "Browser & computer use", patterns: [/browser|computer use|screenshot|click|navigate/i] },
      { label: "Enterprise agents", patterns: [/enterprise|workflow|RPA|copilot|internal/i] },
      { label: "Evals & benchmarks", patterns: [/benchmark|eval|score|SWE-bench|GAIA/i] },
    ],
  }),
  makeTopic({
    slug: "machine-learning",
    category: "ai-tech",
    title: "Machine Learning",
    pageTitle: "Live ML Signals on X — Research, Papers & Training News",
    description:
      "ML research, paper drops, and training infrastructure news from @ylecun, @AndrewYNg, and the ML community on X.",
    keywords: ["machine learning Twitter", "ML research alerts", "deep learning X feed", "AI paper Twitter"],
    intro: "Paper releases, training runs, and ML engineering discourse from researchers and practitioners.",
    watchAccounts: ["ylecun", "AndrewYNg", "hardmaru", "ch402", "karpathy"],
    searchQuery: '("machine learning" OR "deep learning" OR arxiv OR transformer) lang:en -filter:replies',
    pulseLabel: "ML",
  }),
  makeTopic({
    slug: "devtools",
    category: "ai-tech",
    title: "Dev Tools & AI Coding",
    pageTitle: "Live Dev Tool Signals on X — AI Coding, IDEs & CLI",
    description:
      "Cursor, Copilot, CLI tools, and developer productivity chatter — who shipped what in dev tools on X/Twitter.",
    keywords: ["dev tools Twitter", "AI coding alerts", "Cursor IDE Twitter", "developer tools monitor"],
    intro: "IDE updates, AI coding assistants, CLI launches, and dev productivity tips from builders.",
    watchAccounts: ["cursor_ai", "github", "vercel", "swyx", "simonw"],
    searchQuery: '("dev tool" OR "AI coding" OR cursor OR copilot OR CLI) lang:en -filter:replies',
    pulseLabel: "DevTools",
  }),
  makeTopic({
    slug: "hardware",
    category: "ai-tech",
    title: "Hardware & Chips",
    pageTitle: "Live Chip & Hardware Signals on X — GPU, AI Silicon & Semis",
    description:
      "NVIDIA, AMD, Apple silicon, and AI chip news from semis analysts and hardware voices on X/Twitter.",
    keywords: ["semiconductor Twitter", "NVIDIA alerts X", "AI chip news", "GPU Twitter monitor"],
    intro: "GPU supply, chip launches, and semis earnings chatter for AI infrastructure watchers.",
    watchAccounts: ["nvidia", "AMD", "ylecun", "SemiAnalysis", "chipro"],
    searchQuery: "(GPU OR semiconductor OR H100 OR Blackwell OR chip) lang:en -filter:replies",
    pulseLabel: "Chips",
  }),
  makeTopic({
    slug: "robotics",
    category: "ai-tech",
    title: "Robotics",
    pageTitle: "Live Robotics Signals on X — Humanoids, Drones & Automation",
    description:
      "Humanoid robots, autonomous systems, and robotics research updates from labs and founders on X.",
    keywords: ["robotics Twitter", "humanoid robot news", "Boston Dynamics X", "automation alerts"],
    intro: "Robot demos, funding rounds, and autonomy breakthroughs from labs and hardware founders.",
    watchAccounts: ["BostonDynamics", "Tesla", "1X_tech", "Figure_robot", "RealSense"],
    searchQuery: "(robotics OR humanoid OR autonomous robot OR manipulation) lang:en -filter:replies",
    pulseLabel: "Robotics",
  }),

  // ── Crypto & Web3 ───────────────────────────────────────────────
  makeTopic({
    slug: "crypto",
    category: "crypto",
    title: "Crypto & Bitcoin",
    pageTitle: "Live Crypto Signals on X — BTC, ETH & On-Chain Alerts",
    description:
      "Free live crypto signal digest on X/Twitter: @saylor, @VitalikButerin, on-chain accounts, and $BTC/$ETH search.",
    keywords: ["crypto Twitter signals", "Bitcoin Twitter alerts", "monitor @saylor", "BTC news Twitter"],
    intro: "Bitcoin, Ethereum, and crypto market chatter from founders and on-chain analysts.",
    watchAccounts: ["saylor", "VitalikButerin", "cz_binance", "lookonchain", "coinbase"],
    searchQuery: "($BTC OR $ETH OR bitcoin OR crypto) lang:en -filter:replies",
    pulseLabel: "Crypto",
    themeRules: [
      { label: "Bitcoin & macro", patterns: [/\$BTC|bitcoin|halving|ETF|microstrategy/i] },
      { label: "Ethereum & L2", patterns: [/\$ETH|ethereum|layer 2|L2|rollup/i] },
      { label: "Exchange & regulation", patterns: [/SEC|regulation|exchange|binance|coinbase/i] },
      { label: "On-chain flows", patterns: [/whale|inflow|outflow|on-chain|liquidation/i] },
    ],
  }),
  makeTopic({
    slug: "bitcoin",
    category: "crypto",
    title: "Bitcoin Only",
    pageTitle: "Live Bitcoin Signals on X — BTC News, Halving & ETF Flow",
    description:
      "Bitcoin-only discourse: @saylor, macro BTC accounts, ETF flows, and $BTC search on X/Twitter.",
    keywords: ["Bitcoin Twitter alerts", "BTC news X", "monitor @saylor", "Bitcoin ETF Twitter"],
    intro: "Pure Bitcoin narrative — maximalists, macro, ETF flows, and on-chain BTC metrics.",
    watchAccounts: ["saylor", "BitcoinMagazine", "DocumentingBTC", "WClementeIII", "lookonchain"],
    searchQuery: "($BTC OR bitcoin OR BTC OR satoshi) lang:en -filter:replies",
    pulseLabel: "BTC",
  }),
  makeTopic({
    slug: "ethereum",
    category: "crypto",
    title: "Ethereum & L2",
    pageTitle: "Live Ethereum Signals on X — ETH, Rollups & DeFi",
    description:
      "Ethereum upgrades, L2 scaling, and ETH ecosystem news from @VitalikButerin and core builders on X.",
    keywords: ["Ethereum Twitter alerts", "ETH news X", "Vitalik monitor", "L2 rollup Twitter"],
    intro: "ETH upgrades, rollup launches, and ecosystem governance from core contributors.",
    watchAccounts: ["VitalikButerin", "ethereum", "Optimism", "arbitrum", "base"],
    searchQuery: "(ethereum OR $ETH OR rollup OR L2 OR EIP) lang:en -filter:replies",
    pulseLabel: "ETH",
  }),
  makeTopic({
    slug: "defi",
    category: "crypto",
    title: "DeFi & Yield",
    pageTitle: "Live DeFi Signals on X — AMM, Lending & Yield Farming",
    description:
      "DeFi protocol updates, yield strategies, and on-chain DeFi chatter from builders and analysts on X.",
    keywords: ["DeFi Twitter alerts", "yield farming X", "Uniswap monitor", "DeFi protocol news"],
    intro: "Protocol launches, TVL shifts, and yield narratives from DeFi founders and researchers.",
    watchAccounts: ["DefiLlama", "bantg", "haydenzadams", "StaniKulechov", "DefiIgnas"],
    searchQuery: "(DeFi OR yield OR AMM OR liquidity OR TVL) lang:en -filter:replies",
    pulseLabel: "DeFi",
  }),
  makeTopic({
    slug: "solana",
    category: "crypto",
    title: "Solana Ecosystem",
    pageTitle: "Live Solana Signals on X — SOL, Memecoins & dApps",
    description:
      "Solana ecosystem news, memecoin cycles, and builder updates from @solana and SOL community on X.",
    keywords: ["Solana Twitter alerts", "SOL news X", "Solana ecosystem monitor", "memecoin Solana"],
    intro: "SOL price narratives, ecosystem launches, and high-velocity Solana builder discourse.",
    watchAccounts: ["solana", "aeyakovenko", "rajgokal", "phantom", "JupiterExchange"],
    searchQuery: "(solana OR $SOL OR memecoin OR pump.fun) lang:en -filter:replies",
    pulseLabel: "Solana",
  }),
  makeTopic({
    slug: "nft-web3",
    category: "crypto",
    title: "NFT & Web3",
    pageTitle: "Live NFT & Web3 Signals on X — Collections, Gaming & Metaverse",
    description:
      "NFT drops, Web3 gaming, and digital collectibles chatter from creators and marketplaces on X.",
    keywords: ["NFT Twitter alerts", "Web3 gaming X", "OpenSea monitor", "NFT drop news"],
    intro: "Mint announcements, floor price moves, and Web3 gaming launches from creators.",
    watchAccounts: ["opensea", "beeple", "punk6529", "farokh", "Zeneca"],
    searchQuery: "(NFT OR Web3 OR mint OR collection OR metaverse) lang:en -filter:replies",
    pulseLabel: "NFT",
  }),
  makeTopic({
    slug: "web3-dev",
    category: "crypto",
    title: "Web3 Developers",
    pageTitle: "Live Web3 Dev Signals on X — Smart Contracts & dApp Builders",
    description:
      "Solidity, smart contract security, and dApp builder discourse from Web3 engineers on X/Twitter.",
    keywords: ["Web3 developer Twitter", "Solidity alerts", "smart contract X", "dApp builder monitor"],
    intro: "Smart contract patterns, audit findings, and chain dev tooling from Web3 engineers.",
    watchAccounts: ["a16zcrypto", "ethereum", "AlchemyPlatform", "chainlink", "safe"],
    searchQuery: '(Web3 OR solidity OR "smart contract" OR dApp OR EVM) lang:en -filter:replies',
    pulseLabel: "Web3 Dev",
  }),

  // ── Markets & Finance ───────────────────────────────────────────
  makeTopic({
    slug: "trading",
    category: "markets",
    title: "Trading & Markets",
    pageTitle: "Live Stock Market Signals on X/Twitter — Trading & Macro Pulse",
    description:
      "Free live trading signal digest on X: @unusual_whales, macro voices, and market search — flow and earnings chatter.",
    keywords: ["stock market Twitter signals", "trading alerts Twitter", "unusual whales monitor"],
    intro: "Market-moving posts from traders, macro accounts, and live search for active investors.",
    watchAccounts: ["unusual_whales", "zerohedge", "PelosiTracker_", "DeItaone", "elerianm"],
    searchQuery: "(stocks OR trading OR market OR $SPY) lang:en -filter:replies",
    pulseLabel: "Markets",
    themeRules: [
      { label: "Macro & rates", patterns: [/fed|rate|inflation|GDP|jobs|treasury|yield/i] },
      { label: "Options flow", patterns: [/option|call|put|flow|whale|open interest/i] },
      { label: "Earnings", patterns: [/earnings|EPS|guidance|\$[A-Z]{2,5}/i] },
      { label: "Geopolitics", patterns: [/war|sanction|tariff|china|oil|risk-off/i] },
    ],
  }),
  makeTopic({
    slug: "forex",
    category: "markets",
    title: "Forex & FX",
    pageTitle: "Live Forex Signals on X — USD, EUR, JPY & Central Banks",
    description:
      "FX moves, central bank chatter, and currency trader discourse on X/Twitter.",
    keywords: ["forex Twitter alerts", "FX trading X", "USD EUR monitor", "central bank Twitter"],
    intro: "Dollar strength, rate decisions, and FX positioning talk from macro and FX traders.",
    watchAccounts: ["DeItaone", "Fxhedgers", "FirstSquawk", "LiveSquawk", "elerianm"],
    searchQuery: '(forex OR FX OR USD OR EUR OR "central bank") lang:en -filter:replies',
    pulseLabel: "FX",
  }),
  makeTopic({
    slug: "fintech",
    category: "markets",
    title: "Fintech & Payments",
    pageTitle: "Live Fintech Signals on X — Payments, Banking & Neobanks",
    description:
      "Fintech launches, payments infrastructure, and neobank news from founders and VCs on X.",
    keywords: ["fintech Twitter alerts", "payments news X", "neobank monitor", "Stripe Twitter"],
    intro: "Payment rails, banking API shifts, and fintech product launches from industry leaders.",
    watchAccounts: ["stripe", "Plaid", "jack", "fintechfrank", "a16z"],
    searchQuery: "(fintech OR payments OR neobank OR banking API) lang:en -filter:replies",
    pulseLabel: "Fintech",
  }),
  makeTopic({
    slug: "commodities",
    category: "markets",
    title: "Commodities & Oil",
    pageTitle: "Live Commodity Signals on X — Oil, Gold & Energy Markets",
    description:
      "Oil, gold, and commodity market chatter from macro traders and energy analysts on X.",
    keywords: ["commodities Twitter", "oil price alerts X", "gold trading Twitter", "energy markets monitor"],
    intro: "Crude supply, gold flows, and commodity supercycle narratives from macro voices.",
    watchAccounts: ["DeItaone", "zerohedge", "GoldmanSachs", "GoldTelegraph_", "OilPricecom"],
    searchQuery: "(oil OR gold OR commodity OR crude OR $GLD OR OPEC) lang:en -filter:replies",
    pulseLabel: "Commodities",
  }),
  makeTopic({
    slug: "real-estate",
    category: "markets",
    title: "Real Estate",
    pageTitle: "Live Real Estate Signals on X — Housing, Rates & REITs",
    description:
      "Housing market data, mortgage rates, and real estate investor discourse on X/Twitter.",
    keywords: ["real estate Twitter", "housing market alerts", "mortgage rates X", "REIT monitor"],
    intro: "Housing inventory, rate impacts, and commercial RE chatter for property investors.",
    watchAccounts: ["Redfin", "Zillow", "TheRealEstateGuy", "LanceComp", "DeItaone"],
    searchQuery: '(real estate OR housing OR mortgage OR REIT OR "home prices") lang:en -filter:replies',
    pulseLabel: "Real Estate",
  }),

  // ── Startups & Business ─────────────────────────────────────────
  makeTopic({
    slug: "startups",
    category: "business",
    title: "Startups & Founders",
    pageTitle: "Live Startup Signals on X — Founders, Launches & Indie Hackers",
    description:
      "Free live startup signal digest on X/Twitter: @paulg, @levelsio, founders, and launch search.",
    keywords: ["startup Twitter signals", "founder Twitter monitor", "indie hacker alerts"],
    intro: "Founder posts, product launches, and startup discourse from builders you follow.",
    watchAccounts: ["paulg", "Jason", "naval", "sama", "levelsio"],
    searchQuery: '(startup OR founder OR "product launch" OR indie) lang:en -filter:replies',
    pulseLabel: "Startups",
  }),
  makeTopic({
    slug: "saas",
    category: "business",
    title: "SaaS & B2B",
    pageTitle: "Live SaaS Signals on X — B2B Software, Pricing & Growth",
    description:
      "SaaS launches, pricing changes, and B2B growth tactics from founders and operators on X.",
    keywords: ["SaaS Twitter alerts", "B2B software X", "SaaS founder monitor", "ARR MRR Twitter"],
    intro: "Pricing pages, PLG moves, and enterprise SaaS GTM from operators in the space.",
    watchAccounts: ["patio11", "shl", "dharmesh", "HitenShah", "clairejlew"],
    searchQuery: '(SaaS OR B2B OR ARR OR MRR OR "product-led") lang:en -filter:replies',
    pulseLabel: "SaaS",
  }),
  makeTopic({
    slug: "vc-funding",
    category: "business",
    title: "VC & Funding",
    pageTitle: "Live VC Signals on X — Fundraising, Term Sheets & Deals",
    description:
      "Venture capital deals, fundraising announcements, and VC partner takes on X/Twitter.",
    keywords: ["VC Twitter alerts", "fundraising news X", "startup funding monitor", "term sheet Twitter"],
    intro: "Round announcements, VC theses, and cap table chatter from investors and founders.",
    watchAccounts: ["a16z", "naval", "Jason", "paulg", "garrytan"],
    searchQuery: '(VC OR "series A" OR fundraising OR "term sheet" OR raised) lang:en -filter:replies',
    pulseLabel: "VC",
  }),
  makeTopic({
    slug: "ecommerce",
    category: "business",
    title: "E-commerce & DTC",
    pageTitle: "Live E-commerce Signals on X — Shopify, DTC & Amazon",
    description:
      "DTC brand launches, Shopify tactics, and Amazon seller discourse on X/Twitter.",
    keywords: ["ecommerce Twitter alerts", "Shopify monitor X", "DTC brand news", "Amazon seller Twitter"],
    intro: "Store launches, ad creative tests, and DTC playbook posts from brand operators.",
    watchAccounts: ["tobi", "Shopify", "dharmesh", "ecomTom", "TaylorHoliday"],
    searchQuery: '(ecommerce OR Shopify OR DTC OR "direct to consumer" OR "Amazon FBA") lang:en -filter:replies',
    pulseLabel: "E-com",
  }),
  makeTopic({
    slug: "marketing",
    category: "business",
    title: "Marketing & Growth",
    pageTitle: "Live Marketing Signals on X — SEO, Ads & Content",
    description:
      "Growth marketing, SEO, paid ads, and content strategy chatter from marketers on X.",
    keywords: ["marketing Twitter alerts", "growth hacking X", "SEO monitor Twitter", "content marketing feed"],
    intro: "Campaign results, channel tests, and growth loops from marketers shipping in public.",
    watchAccounts: ["randfish", "neilpatel", "garyvee", "amandanat", "Julian"],
    searchQuery: '(marketing OR growth OR SEO OR "paid ads" OR "content strategy") lang:en -filter:replies',
    pulseLabel: "Marketing",
  }),
  makeTopic({
    slug: "indie-hackers",
    category: "business",
    title: "Indie Hackers",
    pageTitle: "Live Indie Hacker Signals on X — Micro-SaaS & Solo Founders",
    description:
      "Solo founder revenue updates, micro-SaaS launches, and build-in-public threads on X.",
    keywords: ["indie hacker Twitter", "micro SaaS alerts", "solo founder X", "build in public monitor"],
    intro: "MRR updates, side project launches, and indie builder playbooks from solo founders.",
    watchAccounts: ["levelsio", "marc_louvion", "tdinh_me", "shl", "peterlevels"],
    searchQuery: '("indie hacker" OR "build in public" OR micro-SaaS OR solopreneur) lang:en -filter:replies',
    pulseLabel: "Indie",
  }),
  makeTopic({
    slug: "remote-work",
    category: "business",
    title: "Remote Work",
    pageTitle: "Live Remote Work Signals on X — Async, Hiring & Culture",
    description:
      "Remote work policy, async culture, and distributed team discourse on X/Twitter.",
    keywords: ["remote work Twitter", "async work alerts", "distributed team X", "WFH monitor"],
    intro: "Return-to-office debates, async workflows, and remote hiring from team leaders.",
    watchAccounts: ["dhh", "jasonfried", "GitLab", "Buffer", "levelsio"],
    searchQuery: '("remote work" OR async OR distributed OR WFH OR "return to office") lang:en -filter:replies',
    pulseLabel: "Remote",
  }),

  // ── Developers ────────────────────────────────────────────────────
  makeTopic({
    slug: "javascript",
    category: "developers",
    title: "JavaScript & TypeScript",
    pageTitle: "Live JavaScript Signals on X — React, Node & TS News",
    description:
      "JavaScript, TypeScript, React, and Node ecosystem updates from core maintainers on X.",
    keywords: ["JavaScript Twitter alerts", "React news X", "TypeScript monitor", "Node.js Twitter"],
    intro: "Framework releases, RFC discussions, and JS ecosystem drama from maintainers.",
    watchAccounts: ["dan_abramov", "wesbos", "swyx", "rauchg", "sindresorhus"],
    searchQuery: "(JavaScript OR TypeScript OR React OR Node.js OR npm) lang:en -filter:replies",
    pulseLabel: "JS",
  }),
  makeTopic({
    slug: "python",
    category: "developers",
    title: "Python",
    pageTitle: "Live Python Signals on X — Django, FastAPI & Data",
    description:
      "Python releases, library updates, and data science tooling news on X/Twitter.",
    keywords: ["Python Twitter alerts", "FastAPI monitor", "Django news X", "Python library Twitter"],
    intro: "PEP discussions, package releases, and Python data stack updates from the community.",
    watchAccounts: ["guido", "raymondh", "simonw", "mkennedy", "t3dotgg"],
    searchQuery: "(Python OR Django OR FastAPI OR pip OR pandas) lang:en -filter:replies",
    pulseLabel: "Python",
  }),
  makeTopic({
    slug: "rust",
    category: "developers",
    title: "Rust",
    pageTitle: "Live Rust Signals on X — Systems, WASM & Performance",
    description:
      "Rust language updates, crate releases, and systems programming discourse on X.",
    keywords: ["Rust Twitter alerts", "Rust lang monitor", "systems programming X", "Rust crate news"],
    intro: "Rust edition news, performance benchmarks, and systems builders shipping in Rust.",
    watchAccounts: ["rustlang", "steveklabnik", "withoutboats", "jamesmunns", "tokio_rs"],
    searchQuery: "(Rust OR rustlang OR cargo OR WASM OR systems programming) lang:en -filter:replies",
    pulseLabel: "Rust",
  }),
  makeTopic({
    slug: "open-source",
    category: "developers",
    title: "Open Source",
    pageTitle: "Live Open Source Signals on X — GitHub, Maintainers & Licenses",
    description:
      "Open source project launches, maintainer burnout debates, and license news on X/Twitter.",
    keywords: ["open source Twitter", "GitHub alerts X", "maintainer monitor", "OSS news Twitter"],
    intro: "Repo stars, license changes, and maintainer sustainability from OSS leaders.",
    watchAccounts: ["github", "natfriedman", "simonw", "sindresorhus", "feross"],
    searchQuery: '("open source" OR OSS OR GitHub OR maintainer OR license) lang:en -filter:replies',
    pulseLabel: "OSS",
  }),
  makeTopic({
    slug: "mobile-dev",
    category: "developers",
    title: "Mobile Development",
    pageTitle: "Live Mobile Dev Signals on X — iOS, Android & Flutter",
    description:
      "iOS, Android, and cross-platform mobile dev news from Apple/Google ecosystem voices on X.",
    keywords: ["iOS dev Twitter", "Android alerts X", "Flutter monitor", "mobile app development Twitter"],
    intro: "App Store policy, SDK updates, and mobile UI patterns from platform developers.",
    watchAccounts: ["Apple", "Android", "FlutterDev", "mattdesl", "jamesm"],
    searchQuery: '(iOS OR Android OR Flutter OR Swift OR Kotlin OR "app store") lang:en -filter:replies',
    pulseLabel: "Mobile",
  }),

  // ── Security & Infra ────────────────────────────────────────────
  makeTopic({
    slug: "cybersecurity",
    category: "security",
    title: "Cybersecurity",
    pageTitle: "Live Cybersecurity Signals on X — CVE, Breaches & Threat Intel",
    description:
      "Security breaches, CVE disclosures, and threat intel from researchers and CISOs on X.",
    keywords: ["cybersecurity Twitter alerts", "CVE monitor X", "data breach news", "infosec Twitter"],
    intro: "Zero-days, breach disclosures, and defensive tactics from security researchers.",
    watchAccounts: ["SwiftOnSecurity", "taviso", "thegrugq", "MalwareTechBlog", "campuscodi"],
    searchQuery: "(CVE OR breach OR vulnerability OR ransomware OR infosec) lang:en -filter:replies",
    pulseLabel: "Security",
    themeRules: [
      { label: "Breaches & incidents", patterns: [/breach|leak|ransomware|compromised|incident/i] },
      { label: "CVE & patches", patterns: [/CVE|patch|zero-day|0day|vulnerability/i] },
      { label: "Threat intel", patterns: [/APT|malware|phishing|botnet|IOC/i] },
      { label: "Defensive tactics", patterns: [/SOC|SIEM|EDR|hardening|blue team/i] },
    ],
  }),
  makeTopic({
    slug: "cloud-infra",
    category: "security",
    title: "Cloud & DevOps",
    pageTitle: "Live Cloud Signals on X — AWS, Kubernetes & SRE",
    description:
      "Cloud outages, Kubernetes updates, and SRE practices from platform engineers on X.",
    keywords: ["cloud Twitter alerts", "AWS monitor X", "Kubernetes news", "DevOps Twitter feed"],
    intro: "Region outages, K8s releases, and infra cost optimization from platform teams.",
    watchAccounts: ["awscloud", "GoogleCloudTech", "Azure", "kubernetesio", "kelseyhightower"],
    searchQuery: '(AWS OR Kubernetes OR DevOps OR SRE OR "cloud outage") lang:en -filter:replies',
    pulseLabel: "Cloud",
  }),

  // ── Policy & News ─────────────────────────────────────────────────
  makeTopic({
    slug: "geopolitics",
    category: "policy",
    title: "Geopolitics",
    pageTitle: "Live Geopolitics Signals on X — War, Trade & Diplomacy",
    description:
      "Breaking geopolitical news, conflict updates, and macro risk from wire services and analysts on X.",
    keywords: ["geopolitics Twitter", "breaking news X alerts", "war news monitor", "macro risk Twitter"],
    intro: "Conflict updates, sanctions, and diplomatic moves from wire accounts and analysts.",
    watchAccounts: ["DeItaone", "zerohedge", "Reuters", "AP", "WarMonitor3"],
    searchQuery: "(geopolitics OR sanctions OR NATO OR conflict OR diplomacy) lang:en -filter:replies",
    pulseLabel: "Geopolitics",
  }),
  makeTopic({
    slug: "tech-policy",
    category: "policy",
    title: "Tech Policy & Regulation",
    pageTitle: "Live Tech Policy Signals on X — AI Law, Antitrust & Privacy",
    description:
      "AI regulation, antitrust, and privacy law discourse from policymakers and tech lawyers on X.",
    keywords: ["tech policy Twitter", "AI regulation alerts", "antitrust X monitor", "GDPR Twitter"],
    intro: "Bill drafts, enforcement actions, and compliance shifts affecting tech companies.",
    watchAccounts: ["EFF", "TechCrunch", "alex", "matthew_d_green", "RMac18"],
    searchQuery: '(regulation OR antitrust OR GDPR OR "AI act" OR compliance) lang:en -filter:replies',
    pulseLabel: "Policy",
  }),

  // ── Science & Health ──────────────────────────────────────────────
  makeTopic({
    slug: "biotech",
    category: "science",
    title: "Biotech & Pharma",
    pageTitle: "Live Biotech Signals on X — FDA, Trials & Gene Therapy",
    description:
      "Biotech trial results, FDA decisions, and pharma news from scientists and investors on X.",
    keywords: ["biotech Twitter alerts", "FDA news X", "clinical trial monitor", "pharma Twitter"],
    intro: "Phase readouts, FDA approvals, and biotech funding from scientists and investors.",
    watchAccounts: ["EricTopol", "AdamFeuerstein", "BioPharmaCatalyst", "statnews", "Nature"],
    searchQuery: '(biotech OR FDA OR "clinical trial" OR pharma OR "gene therapy") lang:en -filter:replies',
    pulseLabel: "Biotech",
  }),
  makeTopic({
    slug: "climate",
    category: "science",
    title: "Climate & Energy",
    pageTitle: "Live Climate Signals on X — Renewables, EV & Carbon",
    description:
      "Climate science, renewable energy, and EV adoption news from researchers and policy voices on X.",
    keywords: ["climate Twitter alerts", "renewable energy X", "EV news monitor", "carbon Twitter"],
    intro: "Policy shifts, grid updates, and climate research from scientists and energy analysts.",
    watchAccounts: ["ClimateHuman", "MichaelEMann", "elonmusk", "IEA", "UNFCCC"],
    searchQuery: "(climate OR renewable OR solar OR EV OR carbon OR emissions) lang:en -filter:replies",
    pulseLabel: "Climate",
  }),
  makeTopic({
    slug: "data-science",
    category: "science",
    title: "Data Science",
    pageTitle: "Live Data Science Signals on X — Analytics, SQL & ML Ops",
    description:
      "Data science workflows, analytics tooling, and MLOps discourse from practitioners on X.",
    keywords: ["data science Twitter", "analytics alerts X", "MLOps monitor", "SQL Twitter feed"],
    intro: "Notebook workflows, dbt launches, and analytics stack choices from data teams.",
    watchAccounts: ["AndrewYNg", "simonw", "huggingface", "databricks", "fchollet"],
    searchQuery: '("data science" OR analytics OR SQL OR dbt OR MLOps) lang:en -filter:replies',
    pulseLabel: "Data",
  }),

  // ── Culture & Lifestyle ───────────────────────────────────────────
  makeTopic({
    slug: "gaming",
    category: "culture",
    title: "Gaming",
    pageTitle: "Live Gaming Signals on X — Esports, AAA & Indie Games",
    description:
      "Game launches, patch notes, and esports news from studios and creators on X/Twitter.",
    keywords: ["gaming Twitter alerts", "esports monitor X", "game launch news", "indie game Twitter"],
    intro: "Patch drops, esports results, and indie game launches from studios and streamers.",
    watchAccounts: ["Xbox", "PlayStation", "Nintendo", "IGN", "Kotaku"],
    searchQuery: '(gaming OR esports OR "game launch" OR patch OR Steam) lang:en -filter:replies',
    pulseLabel: "Gaming",
  }),
  makeTopic({
    slug: "sports",
    category: "culture",
    title: "Sports",
    pageTitle: "Live Sports Signals on X — NFL, NBA, Soccer & F1",
    description:
      "Breaking sports news, trades, and live game chatter from leagues and insiders on X.",
    keywords: ["sports Twitter alerts", "NFL news X", "NBA monitor", "soccer transfer Twitter"],
    intro: "Trades, injuries, and live game reactions from beat reporters and leagues.",
    watchAccounts: ["ESPNNBA", "NFL", "FabrizioRomano", "F1", "BleacherReport"],
    searchQuery: "(NFL OR NBA OR soccer OR F1 OR trade OR injury) lang:en -filter:replies",
    pulseLabel: "Sports",
  }),
  makeTopic({
    slug: "design-ux",
    category: "culture",
    title: "Design & UX",
    pageTitle: "Live Design Signals on X — UI, UX & Product Design",
    description:
      "UI trends, design systems, and product design critique from designers on X/Twitter.",
    keywords: ["UX Twitter alerts", "UI design monitor", "Figma news X", "product design Twitter"],
    intro: "Design system launches, UX patterns, and portfolio drops from product designers.",
    watchAccounts: ["figma", "dribbble", "tobiasah", "jnsgruk", "brian_lovin"],
    searchQuery: '(UX OR UI OR "design system" OR Figma OR "product design") lang:en -filter:replies',
    pulseLabel: "Design",
  }),
  makeTopic({
    slug: "productivity",
    category: "culture",
    title: "Productivity",
    pageTitle: "Live Productivity Signals on X — Tools, Habits & Workflows",
    description:
      "Productivity tools, note-taking apps, and workflow optimization from creators on X.",
    keywords: ["productivity Twitter", "Notion alerts X", "workflow monitor", "second brain Twitter"],
    intro: "Tool comparisons, habit systems, and workflow templates from productivity creators.",
    watchAccounts: ["NotionHQ", "todoist", "fortelabs", "AliAbdaal", "JamesClear"],
    searchQuery: '(productivity OR Notion OR workflow OR habits OR "second brain") lang:en -filter:replies',
    pulseLabel: "Productivity",
  }),
  makeTopic({
    slug: "entertainment",
    category: "culture",
    title: "Entertainment & Film",
    pageTitle: "Live Entertainment Signals on X — Movies, TV & Streaming",
    description:
      "Box office, streaming releases, and Hollywood news from studios and critics on X.",
    keywords: ["entertainment Twitter alerts", "movie news X", "streaming monitor", "Hollywood Twitter"],
    intro: "Trailer drops, box office numbers, and streaming release calendars from entertainment media.",
    watchAccounts: ["Variety", "HollywoodRep", "netflix", "MarvelStudios", "A24"],
    searchQuery: "(movie OR streaming OR box office OR trailer OR Hollywood) lang:en -filter:replies",
    pulseLabel: "Entertainment",
  }),

  // ── XFlux & API (SEO) ─────────────────────────────────────────────
  makeTopic({
    slug: "twitter-api",
    category: "product",
    title: "Twitter / X API",
    pageTitle: "Live Twitter API Signals on X — Developer News & Rate Limits",
    description:
      "Twitter/X API changes, developer policy updates, and integration patterns — monitor API news with XFlux.",
    keywords: ["Twitter API alerts", "X API monitor", "Twitter developer news", "Twitter API rate limit"],
    intro: "API tier changes, deprecations, and developer workarounds from the X dev community.",
    watchAccounts: ["TwitterDev", "XDevelopers", "elonmusk", "simonw", "swyx"],
    searchQuery: '("Twitter API" OR "X API" OR "rate limit" OR twitterdev) lang:en -filter:replies',
    pulseLabel: "X API",
  }),
  makeTopic({
    slug: "webhooks",
    category: "product",
    title: "Webhooks & Integrations",
    pageTitle: "Live Webhook Signals on X — HTTP Callbacks & Event-Driven Apps",
    description:
      "Webhook patterns, event-driven architecture, and integration best practices on X — powered by XFlux monitors.",
    keywords: ["webhook Twitter alerts", "HTTP callback monitor", "event-driven X", "Twitter webhook integration"],
    intro: "Webhook signing, retry logic, and event-driven patterns from backend engineers.",
    watchAccounts: ["stripe", "GitHub", "vercel", "swyx", "simonw"],
    searchQuery: '(webhook OR webhooks OR "event-driven" OR callback OR HMAC) lang:en -filter:replies',
    pulseLabel: "Webhooks",
  }),
  makeTopic({
    slug: "account-monitors",
    category: "product",
    title: "Account Monitors",
    pageTitle: "Live Account Monitor Signals on X — Alerts & Social Listening",
    description:
      "Social listening, @username monitors, and alert workflows on X — see how teams track accounts with XFlux.",
    keywords: ["Twitter account monitor", "social listening X", "username alerts Twitter", "X account tracking"],
    intro: "Monitor patterns, alert stacks, and social listening workflows from growth and ops teams.",
    watchAccounts: ["XDevelopers", "TwitterDev", "levelsio", "patio11", "swyx"],
    searchQuery: '("account monitor" OR "social listening" OR @username OR "twitter alert") lang:en -filter:replies',
    pulseLabel: "Monitors",
  }),

  ...NICHE_SIGNAL_TOPICS,
];
